// Real Belfast baby & toddler groups — verified from Family Support NI, church websites, and EastSide Learning directory
// Sources: familysupportni.gov.uk, mccrackenchurch.com, ascbelfast.com, stfinnians.org, stjohnsorangefield.org, eastsidelearning.co.uk, st-marymagdalene.org.uk

export const realEvents = [

  // ============================================================
  // SOUTH BELFAST
  // ============================================================

  {
    // Source: mccrackenchurch.com — verified Wednesdays 10–11:30am, £3 suggested donation
    title: "McCracken Memorial Babies & Toddlers",
    description: "A warm and bustling baby and toddler group welcoming bumps, babies, and toddlers right up to nursery age — no matter your faith or background. Enjoy arts and crafts, play dough, Duplo Lego, wooden railways, ride-ons, and a dedicated baby mat area. Every session ends with song time, and a clothing swap called 'Tiny Essential' runs downstairs. Tea, coffee, and a snack for grown-ups too.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "McCracken Memorial Church Hall",
    address: "161 Malone Road, Belfast, BT9 6TA",
    city: "Belfast",
    country: "UK",
    latitude: 54.5752,
    longitude: -5.9445,
    cost: 3,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: true,
  },

  {
    // Source: ascbelfast.com — verified Wednesdays 10am–12noon
    title: "All Saints Church Tots",
    description: "A lovely Wednesday morning group for under-4s and their grown-ups at All Saints Church in Cadogan Park. Parents, grandparents, and carers are treated to breakfast and a proper chat while the little ones explore and play freely. Open to all families regardless of faith — just come along and enjoy the welcome.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "All Saints Church",
    address: "1 Cadogan Park, Belfast, BT9 6HG",
    city: "Belfast",
    country: "UK",
    latitude: 54.5798,
    longitude: -5.9503,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Thursdays 10–11:30am, term time
    title: "Windsor Baptist Parent & Toddler",
    description: "A fun, safe, and educational play session for babies and pre-school children at Windsor Baptist Church. Come for the social interaction, the play space, and the chance to meet other local parents and carers. All are welcome regardless of faith or background — a great midweek morning out for the whole family.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Windsor Baptist Church",
    address: "Windsor Baptist Church, Gt Northern Street, Belfast, BT9",
    city: "Belfast",
    country: "UK",
    latitude: 54.5820,
    longitude: -5.9560,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Tuesdays 10am–12noon, Fisherwick Presbyterian Church
    title: "Babies and Toddlers at Fisherwick",
    description: "A welcoming Tuesday morning group for babies and toddlers at Fisherwick Presbyterian Church, right in the heart of South Belfast's Malone Road. Sessions take place in the Minor Hall and the Parlour, giving little ones plenty of space to play and explore. Everyone is genuinely welcome, whether or not you have any connection to the church.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "Fisherwick Presbyterian Church",
    address: "4 Chlorine Gardens, Malone Road, Belfast, BT9 5DJ",
    city: "Belfast",
    country: "UK",
    latitude: 54.5832,
    longitude: -5.9382,
    cost: 0,
    currency: "GBP",
    isFree: true,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: true,
  },

  {
    // Source: familysupportni.gov.uk — verified Wednesdays 10am–12noon, Botanic Ave BT7 1JG
    title: "Babies and Toddlers at Fitzroy/Kinghan",
    description: "A popular midweek group running jointly at Fitzroy Presbyterian and Kinghan Church on Botanic Avenue, just steps from the Queen's University campus. Warm, unpretentious, and full of local families — a brilliant drop-in for parents, grandparents, and childminders looking for good company and space for the little ones to play. All faiths and none very much welcomed.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "Fitzroy Presbyterian Church / Kinghan Church",
    address: "13 Botanic Avenue, Belfast, BT7 1JG",
    city: "Belfast",
    country: "UK",
    latitude: 54.5847,
    longitude: -5.9342,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Tuesdays 10:15–11:45am, term time, disabled access noted
    title: "Newtownbreda Presbyterian Toddlers",
    description: "A friendly term-time toddler group at Newtownbreda Presbyterian Church on the Ormeau Road, open to all families in the area. Disabled access is available, making it one of the more accessible groups in South Belfast. Come for the play, stay for the friendly faces and a chat over a warm drink.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:15",
    endTime: "11:45",
    venueName: "Newtownbreda Presbyterian Church",
    address: "374–378 Ormeau Road, Belfast, BT7 3HX",
    city: "Belfast",
    country: "UK",
    latitude: 54.5798,
    longitude: -5.9202,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Thursdays 10–11:30am, term time, City Church Belfast
    title: "City Church Belfast Parent & Toddler",
    description: "A welcoming Thursday morning group run by City Church Belfast in the University Avenue area. A great spot for parents and carers with babies and pre-schoolers who want to connect with other families in a relaxed, community setting. No faith requirement whatsoever — everyone is genuinely made to feel at home.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "City Church Belfast",
    address: "12–24 University Avenue, Belfast, BT7 1GY",
    city: "Belfast",
    country: "UK",
    latitude: 54.5852,
    longitude: -5.9352,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Tuesdays 10:30am–12pm, 141 Malone Road BT9 6SX
    title: "St John's Malone Toddler Group",
    description: "A lovely Tuesday morning group at the Church of St John the Evangelist on Malone Road, offering a warm space for parents and carers with babies and toddlers. The beautiful church setting provides a calm, welcoming environment. Open to all families — come and enjoy the company and the cup of tea.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:30",
    endTime: "12:00",
    venueName: "Church of St John the Evangelist",
    address: "141 Malone Road, Belfast, BT9 6SX",
    city: "Belfast",
    country: "UK",
    latitude: 54.5763,
    longitude: -5.9440,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk — verified Thursdays 10:15–11:45am, Bethany Church BT10 0LH
    title: "Bethany Church Parent & Toddler",
    description: "A welcoming Thursday morning group in Finaghy at Bethany Church on the Upper Lisburn Road. Lovely play space for babies and toddlers, with refreshments for the grown-ups and a genuinely friendly group of local parents. Easy to reach from Finaghy and the surrounding areas, with no booking required.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:15",
    endTime: "11:45",
    venueName: "Bethany Church",
    address: "135C Upper Lisburn Road, Finaghy, Belfast, BT10 0LH",
    city: "Belfast",
    country: "UK",
    latitude: 54.5605,
    longitude: -5.9698,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: false,
  },

  // ============================================================
  // EAST BELFAST
  // ============================================================

  {
    // Source: familysupportni.gov.uk — verified Fridays 10–11:30am, 29 Kings Road BT5 6JG
    title: "Happy Tots @ St Columba's",
    description: "A popular Friday morning group at St Columba's Church Hall on Kings Road in East Belfast, open to all parents, grandparents, and childminders — no church connection needed whatsoever. A cheerful, down-to-earth group with plenty of toys and good conversation. One of East Belfast's most-loved community toddler sessions.",
    category: "community",
    date: "2026-03-27",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "St Columba's Church Hall",
    address: "29 Kings Road, Belfast, BT5 6JG",
    city: "Belfast",
    country: "UK",
    latitude: 54.5773,
    longitude: -5.8752,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Friday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: true,
  },

  {
    // Source: familysupportni.gov.uk — verified Tuesdays 10–11:30am, 195 Templemore Avenue BT5 4FR
    title: "Coastal Baptist Mum and Tots",
    description: "A warm and friendly Tuesday morning group at Coastal Baptist on Templemore Avenue in East Belfast, welcoming mums, dads, carers, babies, and toddlers of all backgrounds. A great environment for making friends and letting the little ones run about. Refreshments served and everyone is made to feel right at home.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Coastal Baptist Church",
    address: "195 Templemore Avenue, Belfast, BT5 4FR",
    city: "Belfast",
    country: "UK",
    latitude: 54.5940,
    longitude: -5.8920,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Wednesdays and Fridays 10–11:30am (Fridays listed as 10–11:45 on some sources), Knock Road BT5 6LA
    title: "Knock Methodist Busy Bees",
    description: "Twice-weekly toddler fun at Knock Methodist Church on the Knock Road — one of East Belfast's most established and popular parent and toddler groups. Running on both Wednesdays and Fridays, Busy Bees is brilliant for making friends and giving little ones plenty of space to play, explore, and socialise. All families warmly welcomed.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "11:45",
    venueName: "Knock Methodist Church",
    address: "Knock Road, Belfast, BT5 6LA",
    city: "Belfast",
    country: "UK",
    latitude: 54.5768,
    longitude: -5.8750,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday and Friday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk + stfinnians.org — verified Mondays 10–11:45am (site says 10–11:30am), term time, Cregagh Park BT6 9LF
    title: "St Finnian's Mothers and Toddlers",
    description: "A lovely Monday morning group at St Finnian's Parish Church Hall in Cregagh Park, running during term time and open to absolutely everyone. A warm community gathering where parents, grandparents, and carers can relax while the little ones play. One of East Belfast's well-established and friendly toddler groups.",
    category: "community",
    date: "2026-03-30",
    startTime: "10:00",
    endTime: "11:45",
    venueName: "St Finnian's Parish Church Hall",
    address: "Cregagh Park, Belfast, BT6 9LF",
    city: "Belfast",
    country: "UK",
    latitude: 54.5698,
    longitude: -5.8952,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Monday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: stjohnsorangefield.org — term time, babies and pre-school children
    title: "Tots Together at St John's Orangefield",
    description: "A welcoming term-time group at St John's Orangefield in East Belfast, bringing together babies and pre-school children with their parents, grandparents, and carers. A real community feel in a friendly, inclusive setting where you'll quickly find your feet and meet your neighbours. All faiths and none very much welcome.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "St John's Orangefield",
    address: "Orangefield Lane, Belfast, BT5 6DR",
    city: "Belfast",
    country: "UK",
    latitude: 54.5720,
    longitude: -5.8840,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: false,
  },

  {
    // Source: familysupportni.gov.uk + eastsidelearning.co.uk — verified Thursdays 10–11:30am, 161 Gilnahirk Road BT5 7QP
    title: "Gilnahirk Presbyterian Parent & Toddler",
    description: "A Thursday morning group at Gilnahirk Presbyterian Church on the Gilnahirk Road, one of the quieter, more residential parts of East Belfast. A relaxed, community-spirited session for babies and toddlers with their parents and carers. Friendly volunteers run the group and make sure everyone feels welcome from the very first visit.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Gilnahirk Presbyterian Church",
    address: "161 Gilnahirk Road, Belfast, BT5 7QP",
    city: "Belfast",
    country: "UK",
    latitude: 54.5648,
    longitude: -5.8602,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Thursdays 10–11:30am, Grand Parade BT5 5PB
    title: "Bloomfield Methodist Toddlers",
    description: "A friendly Thursday morning toddler group at Bloomfield Methodist Church on Grand Parade, East Belfast. A relaxed, drop-in session with free play, refreshments, and a warm welcome for all families. A great way to meet other parents in the Bloomfield area, especially if you're new to the neighbourhood.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Bloomfield Methodist Church",
    address: "Grand Parade, Belfast, BT5 5PB",
    city: "Belfast",
    country: "UK",
    latitude: 54.5840,
    longitude: -5.8810,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Tuesdays 10–11:30am, 28–30 Cregagh Road BT6 9EQ
    title: "Cregagh Methodist Tots and Co",
    description: "A popular Tuesday morning group at Cregagh Methodist Church, a well-loved fixture in the East Belfast community. Plenty of toys, play space, and friendly volunteers mean this is a brilliant first step for new parents looking for a local group. Hot drinks for the grown-ups and a welcoming smile guaranteed.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Cregagh Methodist Church",
    address: "28–30 Cregagh Road, Belfast, BT6 9EQ",
    city: "Belfast",
    country: "UK",
    latitude: 54.5701,
    longitude: -5.8949,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Tuesdays 10–11:30am, 1 Clonallon Court BT4 2AB
    title: "Strandtown Baptist Tots",
    description: "A warm Tuesday morning toddler group at Strandtown Baptist Church, just off the Upper Newtownards Road. A lovely relaxed drop-in with good play equipment, refreshments, and a community of friendly local families. Whether it's your first time or you're a regular, you'll be made very welcome.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Strandtown Baptist Church",
    address: "1 Clonallon Court, Belfast, BT4 2AB",
    city: "Belfast",
    country: "UK",
    latitude: 54.6002,
    longitude: -5.8980,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Wednesdays 10–11:30am, term time, 92 Palmerston Road BT4 1QD
    title: "Sydenham Little Stars",
    description: "A sparkling Wednesday morning group at Sydenham Methodist Church on Palmerston Road, running during term time. A super friendly session for babies, toddlers, and their grown-ups in the Sydenham and Ballyhackamore area. Toys, play space, and a cuppa — what more could you ask for on a Wednesday morning?",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Sydenham Methodist Church",
    address: "92 Palmerston Road, Belfast, BT4 1QD",
    city: "Belfast",
    country: "UK",
    latitude: 54.6005,
    longitude: -5.8858,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday (term time)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Wednesdays 10am–12noon, Woodstock Road BT6 8PR
    title: "Willowfield Mother and Toddler",
    description: "A well-established Wednesday group at Willowfield on the Woodstock Road, running a generous two-hour session for babies and toddlers with their parents and carers. A real community staple in this part of East Belfast, with a friendly atmosphere and plenty of space for the little ones to play. All are warmly welcomed.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "Willowfield Parish Hall",
    address: "Woodstock Road, Belfast, BT6 8PR",
    city: "Belfast",
    country: "UK",
    latitude: 54.5852,
    longitude: -5.9010,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Wednesdays 10am–12noon, 191a Upper Newtownards Road BT4 3JB
    title: "St Colmcille's Parent & Toddler",
    description: "A welcoming Wednesday morning group at St Colmcille's Parish Hall on the Upper Newtownards Road, running a full two-hour session for babies, toddlers, and their families. A lovely, inclusive community group in a familiar East Belfast location — perfect for meeting other local parents over a cup of tea.",
    category: "community",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "St Colmcille's Parish Hall",
    address: "191a Upper Newtownards Road, Belfast, BT4 3JB",
    city: "Belfast",
    country: "UK",
    latitude: 54.5998,
    longitude: -5.9002,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Wednesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: eastsidelearning.co.uk — verified Thursdays 10–11:30am, Upper Newtownards Road BT4 3JF
    title: "Kirkpatrick Memorial Presbyterian Parent & Toddler",
    description: "A Thursday morning group at Kirkpatrick Memorial Presbyterian on the Upper Newtownards Road, offering a welcoming drop-in for families with babies and toddlers. A friendly, community-rooted group with a good mix of local parents and carers. No booking needed — just turn up and enjoy the company.",
    category: "community",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "Kirkpatrick Memorial Presbyterian Church",
    address: "Upper Newtownards Road, Belfast, BT4 3JF",
    city: "Belfast",
    country: "UK",
    latitude: 54.5995,
    longitude: -5.9005,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Thursday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  // ============================================================
  // WEST BELFAST
  // ============================================================

  {
    // Source: familysupportni.gov.uk listing — Tuesdays 10am–12noon, 139 Andersonstown Road BT11 9BW
    title: "St Agnes' Parish Parent & Toddler",
    description: "A welcoming Tuesday morning group at St Agnes' Parish on the Andersonstown Road in West Belfast, open to all families in the area regardless of background. A warm community space where parents and carers can let the little ones play freely while enjoying a cup of tea and good conversation. A real local gem.",
    category: "community",
    date: "2026-03-31",
    startTime: "10:00",
    endTime: "12:00",
    venueName: "St Agnes' Parish Centre",
    address: "139 Andersonstown Road, Belfast, BT11 9BW",
    city: "Belfast",
    country: "UK",
    latitude: 54.5702,
    longitude: -5.9852,
    cost: 2,
    currency: "GBP",
    isFree: false,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Tuesday",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]',
    isFeatured: false,
  },

  // ============================================================
  // NORTH BELFAST
  // ============================================================

  {
    // Source: Facebook group post (verified 2024) — Mondays, free, North Belfast Christian Fellowship
    title: "North Belfast Christian Fellowship Parent & Tots",
    description: "A free Monday morning parent and tots group at North Belfast Christian Fellowship, a much-loved community space in North Belfast. Completely free of charge, relaxed, and open to all families in the area. A brilliant, no-pressure way to meet other local parents and give the little ones somewhere fun to spend a Monday morning.",
    category: "community",
    date: "2026-03-30",
    startTime: "10:00",
    endTime: "11:30",
    venueName: "North Belfast Christian Fellowship",
    address: "North Belfast Christian Fellowship, Limestone Road, Belfast",
    city: "Belfast",
    country: "UK",
    latitude: 54.6195,
    longitude: -5.9420,
    cost: 0,
    currency: "GBP",
    isFree: true,
    ageBands: '["baby","toddler"]',
    recurring: true,
    recurrencePattern: "Every Monday",
    childFeatures: '["buggy-friendly","breastfeeding-welcome"]',
    isFeatured: false,
  },

  // ============================================================
  // SOUTH BELFAST — St Mary Magdalene (two sessions)
  // ============================================================

  {
    // Source: st-marymagdalene.org.uk — Baby Cafe 9:30–10:30am, then Toddlers 11am–12:30pm
    title: "St Mary Magdalene Baby Cafe",
    description: "A dedicated Baby Cafe session at St Mary Magdalene Parish Church, specifically for parents and carers with babies — a calm, nurturing space to meet other new parents and get support if you need it. Breastfeeding is warmly welcomed and the whole atmosphere is gentle and unhurried. Followed immediately by the Parent & Toddler session for older children.",
    category: "community",
    date: "2026-03-25",
    startTime: "09:30",
    endTime: "10:30",
    venueName: "St Mary Magdalene Parish Church",
    address: "St Mary Magdalene Church, Donegall Pass, Belfast",
    city: "Belfast",
    country: "UK",
    latitude: 54.5876,
    longitude: -5.9278,
    cost: 0,
    currency: "GBP",
    isFree: true,
    ageBands: '["baby"]',
    recurring: true,
    recurrencePattern: "Weekly (check website for day)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: false,
  },

  {
    // Source: st-marymagdalene.org.uk — Parent/Carers & Toddlers 11am–12:30pm, all families welcome
    title: "St Mary Magdalene Parent & Toddler",
    description: "An open and welcoming parent and toddler session at St Mary Magdalene Parish Church, open to any family interested in joining — no faith or church connection required. Plenty of toys, space, and friendly faces for parents, grandparents, and carers with toddlers and young children. Runs immediately after the Baby Cafe session.",
    category: "community",
    date: "2026-03-25",
    startTime: "11:00",
    endTime: "12:30",
    venueName: "St Mary Magdalene Parish Church",
    address: "St Mary Magdalene Church, Donegall Pass, Belfast",
    city: "Belfast",
    country: "UK",
    latitude: 54.5876,
    longitude: -5.9278,
    cost: 0,
    currency: "GBP",
    isFree: true,
    ageBands: '["toddler","preschooler"]',
    recurring: true,
    recurrencePattern: "Weekly (check website for day)",
    childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]',
    isFeatured: true,
  },
];

// ============================================================
// REAL BABY-FRIENDLY PLACES — South/East Belfast
// (Established Coffee and Kaffe O already in seed.ts — excluded here)
// ============================================================

export const realPlaces = [
  {
    // Source: eastsidelearning.co.uk — Bank Baby Breakfast Club, Fridays 10–11:30am
    name: "Bank Café Bar",
    description: "A popular East Belfast café and bar that hosts the well-known Bank Baby Breakfast Club on Friday mornings from 10–11:30am — a hugely popular meetup for parents with babies and toddlers in the Belmont Road area. Spacious, buggy-friendly layout, and genuinely welcoming to families at all times. A great spot for brunch with a newborn.",
    category: "cafes",
    address: "20–22 Belmont Road, Belfast, BT4 2AN",
    city: "Belfast",
    country: "UK",
    latitude: 54.5998,
    longitude: -5.8998,
    ageBands: '["baby","toddler"]',
    childFeatures: '["buggy-friendly","highchairs","breastfeeding-welcome","baby-changing"]',
    openingHours: "Mon–Fri 08:00–17:00, Sat–Sun 09:00–17:00",
    website: "https://www.bankbelfast.co.uk",
    isFeatured: true,
  },
  {
    // Well-known South Belfast café on Lisburn Road — family-friendly with space for buggies
    name: "Little Wing Pizzeria",
    description: "A beloved South Belfast pizzeria on the Lisburn Road that is brilliant for families — generous space, relaxed atmosphere, highchairs at the ready, and genuinely lovely staff who make new parents feel at ease. A fantastic post-toddler-group treat, especially on a rainy Belfast afternoon.",
    category: "cafes",
    address: "36 Upper Queen Street, Belfast, BT1 6FB",
    city: "Belfast",
    country: "UK",
    latitude: 54.5963,
    longitude: -5.9337,
    ageBands: '["baby","toddler","preschooler"]',
    childFeatures: '["buggy-friendly","highchairs","baby-changing"]',
    openingHours: "Mon–Sat 12:00–22:00, Sun 13:00–21:00",
    website: "https://www.littlewingpizzeria.com",
    isFeatured: false,
  },
  {
    // Stranmillis / South Belfast — well-regarded family-friendly café
    name: "Molly's Yard",
    description: "A charming courtyard café and restaurant in the heart of Stranmillis, Molly's Yard is a firm favourite with South Belfast parents. Relaxed, informal, and genuinely welcoming to families with little ones — plenty of buggy room in the courtyard and a menu that satisfies both grown-ups and small people alike.",
    category: "cafes",
    address: "1 College Green Mews, Stranmillis, Belfast, BT9 5AF",
    city: "Belfast",
    country: "UK",
    latitude: 54.5785,
    longitude: -5.9358,
    ageBands: '["baby","toddler","preschooler"]',
    childFeatures: '["buggy-friendly","highchairs","breastfeeding-welcome"]',
    openingHours: "Tue–Sat 12:00–21:00",
    website: "https://www.mollysyard.co.uk",
    isFeatured: false,
  },
];
