import { db } from "./storage";
import { events, places, userProfiles, sponsors, reactions, reviews } from "@shared/schema";
import { newEvents, newPlaces } from "./seed-new-locations";
import { realEvents, realPlaces } from "./seed-real-groups";

export function seedDatabase() {
  // Check if already seeded
  const existingEvents = db.select().from(events).all();
  if (existingEvents.length > 0) return;

  // Create default profile
  db.insert(userProfiles).values({
    locationCity: "Belfast",
    locationLat: 54.5973,
    locationLng: -5.9301,
    preferredCurrency: "GBP",
    distanceRadius: 5,
  }).run();

  // ============ EVENTS ============

  const seedEvents = [
    // BELFAST
    { title: "Tiny Sensory Explorers", description: "A gentle sensory play session for babies. Explore different textures, lights, and sounds in a calm, nurturing environment. Perfect for developing those little senses.", category: "classes", date: "2026-03-26", startTime: "10:00", endTime: "11:00", venueName: "Ormeau Community Centre", address: "Ormeau Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5843, longitude: -5.9210, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Mums & Beans Coffee Morning", description: "A friendly, relaxed coffee morning for mums with little ones. Great coffee, warm conversation, and space for the babies to play. No booking needed, just turn up.", category: "social", date: "2026-03-27", startTime: "10:30", endTime: "12:00", venueName: "Kaffe O", address: "Stranmillis Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5770, longitude: -5.9350, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","highchairs","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Rhyme Time", description: "Sing-along session with nursery rhymes, action songs, and gentle music. A wonderful way to bond with your baby through rhythm and melody.", category: "music", date: "2026-03-25", startTime: "11:00", endTime: "11:30", venueName: "Belfast Central Library", address: "Royal Avenue, Belfast", city: "Belfast", country: "UK", latitude: 54.6007, longitude: -5.9304, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Buggy Walk at Botanic Gardens", description: "Join other parents for a gentle guided walk through the beautiful Botanic Gardens. Fresh air, lovely scenery, and great company at your own pace.", category: "outdoor", date: "2026-03-26", startTime: "09:30", endTime: "10:30", venueName: "Botanic Gardens", address: "Botanic Avenue, Belfast", city: "Belfast", country: "UK", latitude: 54.5847, longitude: -5.9316, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","parking"]', isFeatured: false },
    { title: "Little Splashers Baby Swimming", description: "Introduce your baby to the water in a warm, shallow pool. Qualified instructors guide you through gentle water confidence exercises. Bring a swim nappy.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:30", venueName: "Falls Leisure Centre", address: "Falls Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5951, longitude: -5.9534, cost: 6, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["baby-changing","parking"]', isFeatured: false },
    { title: "Postnatal Yoga for Mums", description: "A gentle yoga class designed specifically for postnatal recovery. Babies welcome to lie beside you on the mat. Focuses on core strengthening and relaxation.", category: "wellness", date: "2026-03-25", startTime: "13:00", endTime: "14:00", venueName: "The Flow Studio", address: "Lisburn Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5760, longitude: -5.9450, cost: 12, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Toddler Art Explorers", description: "A messy play and art session for curious toddlers. Paint, playdough, collage and more. Wear old clothes and prepare to get mucky. All materials provided.", category: "arts", date: "2026-03-27", startTime: "10:00", endTime: "11:00", venueName: "The MAC", address: "Exchange Street West, Belfast", city: "Belfast", country: "UK", latitude: 54.6005, longitude: -5.9240, cost: 7, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    { title: "Story Explorers", description: "An interactive storytelling session where little ones can join in with props, puppets, and songs. Each week features a different picture book adventure.", category: "storytime", date: "2026-03-26", startTime: "10:30", endTime: "11:15", venueName: "Lisburn Road Library", address: "Lisburn Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5745, longitude: -5.9475, cost: 0, currency: "GBP", isFree: true, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    { title: "Mini Movers Dance Class", description: "A fun, energetic dance and movement class for pre-schoolers. Action songs, creative dance, and imaginative play all wrapped into a joyful 45 minutes.", category: "classes", date: "2026-03-28", startTime: "11:00", endTime: "11:45", venueName: "Belvoir Activity Centre", address: "Belvoir Park, Belfast", city: "Belfast", country: "UK", latitude: 54.5560, longitude: -5.9400, cost: 6, currency: "GBP", isFree: false, ageBands: '["preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["parking","baby-changing"]', isFeatured: false },
    { title: "Spring Nature Trail", description: "A guided nature walk for families with young children. Spot spring flowers, birds, and wildlife along the Lagan Towpath. Bug pots and magnifying glasses provided.", category: "outdoor", date: "2026-03-29", startTime: "10:00", endTime: "11:30", venueName: "Lagan Towpath", address: "Stranmillis, Belfast", city: "Belfast", country: "UK", latitude: 54.5700, longitude: -5.9350, cost: 0, currency: "GBP", isFree: true, ageBands: '["toddler","preschooler"]', recurring: false, childFeatures: '["buggy-friendly"]', isFeatured: true },

    // DUBLIN
    { title: "Baby Sensory Dublin", description: "Award-winning sensory development classes for babies from birth. Explore lights, sounds, textures and music in a stimulating yet gentle session.", category: "classes", date: "2026-03-26", startTime: "10:00", endTime: "11:00", venueName: "Maldron Hotel Parnell Square", address: "Parnell Square, Dublin 1", city: "Dublin", country: "Ireland", latitude: 53.3538, longitude: -6.2638, cost: 12, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]', isFeatured: true },
    { title: "Mum & Baby Yoga in the Park", description: "Outdoor yoga designed for postnatal mums with babies. Stretches, breathing exercises, and gentle strengthening moves in the beautiful surroundings of Merrion Square.", category: "wellness", date: "2026-03-27", startTime: "10:30", endTime: "11:30", venueName: "Merrion Square Park", address: "Merrion Square, Dublin 2", city: "Dublin", country: "Ireland", latitude: 53.3399, longitude: -6.2491, cost: 15, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","breastfeeding-welcome"]', isFeatured: false },
    { title: "Toddler Tunes Music Class", description: "A lively music and movement class for toddlers. Instruments, singing, dancing, and loads of fun. Perfect for building confidence and social skills through music.", category: "music", date: "2026-03-25", startTime: "09:30", endTime: "10:15", venueName: "Smock Alley Theatre", address: "Exchange Street Lower, Dublin 8", city: "Dublin", country: "Ireland", latitude: 53.3454, longitude: -6.2738, cost: 10, currency: "EUR", isFree: false, ageBands: '["toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    { title: "Phoenix Park Playdate", description: "A free, casual meetup for parents and little ones in Phoenix Park. Bring a picnic blanket and toys. The deer are always a hit with the toddlers.", category: "social", date: "2026-03-28", startTime: "11:00", endTime: "13:00", venueName: "Phoenix Park", address: "Phoenix Park, Dublin 8", city: "Dublin", country: "Ireland", latitude: 53.3559, longitude: -6.3298, cost: 0, currency: "EUR", isFree: true, ageBands: '["baby","toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","parking"]', isFeatured: false },
    { title: "Little Readers Story Time", description: "A cosy story time session at Pearse Street Library. Picture books, puppet shows and sing-alongs for the under-5s. A calm, welcoming space.", category: "storytime", date: "2026-03-25", startTime: "11:00", endTime: "11:30", venueName: "Pearse Street Library", address: "Pearse Street, Dublin 2", city: "Dublin", country: "Ireland", latitude: 53.3432, longitude: -6.2475, cost: 0, currency: "EUR", isFree: true, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Messy Play Dublin", description: "Get ready to get messy. Paint, slime, sensory trays, sand and water play in a purpose-built space. Aprons provided but wear clothes you don't mind getting colourful.", category: "arts", date: "2026-03-26", startTime: "14:00", endTime: "15:00", venueName: "Imaginosity", address: "Beacon South Quarter, Sandyford, Dublin 18", city: "Dublin", country: "Ireland", latitude: 53.2710, longitude: -6.2187, cost: 8, currency: "EUR", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', isFeatured: false },
    { title: "Buggy Fit Bootcamp", description: "A high-energy outdoor fitness class for mums with buggies. Cardio, strength, and core exercises while your baby enjoys the ride. All fitness levels welcome.", category: "wellness", date: "2026-03-28", startTime: "09:30", endTime: "10:30", venueName: "Herbert Park", address: "Ballsbridge, Dublin 4", city: "Dublin", country: "Ireland", latitude: 53.3276, longitude: -6.2296, cost: 10, currency: "EUR", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly"]', isFeatured: true },

    // LONDON
    { title: "Baby Discovery at the Science Museum", description: "A specially designed interactive session for babies and their parents in the museum's sensory garden. Explore light, sound and texture with museum educators.", category: "daysout", date: "2026-03-26", startTime: "10:30", endTime: "11:15", venueName: "Science Museum", address: "Exhibition Road, South Kensington, London SW7", city: "London", country: "UK", latitude: 51.4978, longitude: -0.1745, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Coram's Fields Toddler Playgroup", description: "A free outdoor playgroup in London's best-kept secret park. Sandpit, paddling pool in summer, and a wonderful under-5s playground. Adults must be accompanied by a child.", category: "outdoor", date: "2026-03-25", startTime: "10:00", endTime: "12:00", venueName: "Coram's Fields", address: "93 Guilford Street, London WC1N", city: "London", country: "UK", latitude: 51.5244, longitude: -0.1210, cost: 0, currency: "GBP", isFree: true, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every weekday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },
    { title: "Baby Massage & Relaxation", description: "Learn soothing massage techniques for your baby in a small, intimate group. Helps with colic, sleep, and bonding. Organic oils provided.", category: "classes", date: "2026-03-27", startTime: "14:00", endTime: "15:00", venueName: "Mama & Me Studio", address: "Islington, London N1", city: "London", country: "UK", latitude: 51.5362, longitude: -0.1033, cost: 15, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Puppet Show at the Little Angel", description: "A magical puppet show designed for children aged 2-5. Beautiful handcrafted puppets bring stories to life in an intimate, purpose-built theatre.", category: "music", date: "2026-03-29", startTime: "11:00", endTime: "11:45", venueName: "Little Angel Theatre", address: "Dagmar Passage, Islington, London N1", city: "London", country: "UK", latitude: 51.5401, longitude: -0.1031, cost: 12, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: false, childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    { title: "NCT Breastfeeding Support Drop-in", description: "A warm, judgement-free space for mums who are breastfeeding or expressing. Experienced peer supporters on hand. Tea and biscuits provided.", category: "social", date: "2026-03-25", startTime: "13:00", endTime: "15:00", venueName: "St Mary's Church Hall", address: "Stoke Newington, London N16", city: "London", country: "UK", latitude: 51.5613, longitude: -0.0783, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Dinosaur Discovery Trail", description: "A self-guided trail through the amazing Natural History Museum dinosaur galleries. Free trail map at the entrance. Little ones love the animatronic T-Rex.", category: "daysout", date: "2026-03-28", startTime: "10:00", endTime: "16:00", venueName: "Natural History Museum", address: "Cromwell Road, South Kensington, London SW7", city: "London", country: "UK", latitude: 51.4967, longitude: -0.1764, cost: 0, currency: "GBP", isFree: true, ageBands: '["preschooler"]', recurring: false, childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Music Bugs Baby Class", description: "Multi-sensory music class using instruments, bubbles, parachutes and props. A lovely 45 minutes of bonding through music. Book in advance.", category: "music", date: "2026-03-26", startTime: "10:00", endTime: "10:45", venueName: "Dulwich Community Centre", address: "East Dulwich, London SE22", city: "London", country: "UK", latitude: 51.4560, longitude: -0.0714, cost: 10, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },

    // EDINBURGH
    { title: "Bookbug Baby Session", description: "Scotland's wonderful free baby reading programme. Songs, rhymes, and stories for babies and toddlers. Receive a free book bag to take home.", category: "storytime", date: "2026-03-25", startTime: "10:30", endTime: "11:00", venueName: "Edinburgh Central Library", address: "George IV Bridge, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9487, longitude: -3.1918, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: true },
    { title: "Wee Explorers at the Botanics", description: "A nature discovery session for under-5s in the Royal Botanic Garden. Leaf hunts, bug spotting, and sensory exploration in the glasshouses.", category: "outdoor", date: "2026-03-26", startTime: "10:00", endTime: "11:00", venueName: "Royal Botanic Garden Edinburgh", address: "Inverleith Row, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9652, longitude: -3.2088, cost: 5, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },
    { title: "Tiny Dancers Ballet", description: "An enchanting introduction to ballet for pre-schoolers. Learn basic positions, movement, and musicality through imaginative play and fairy tales.", category: "classes", date: "2026-03-28", startTime: "09:30", endTime: "10:15", venueName: "Dance Base", address: "Grassmarket, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9475, longitude: -3.1962, cost: 8, currency: "GBP", isFree: false, ageBands: '["preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["baby-changing"]', isFeatured: false },
    { title: "Edinburgh Mums Brunch", description: "A monthly brunch for mums with babies at a lovely family-friendly restaurant. Relax, chat, and enjoy proper food while the little ones play.", category: "social", date: "2026-03-29", startTime: "11:00", endTime: "13:00", venueName: "The Pantry", address: "Stockbridge, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9587, longitude: -3.2104, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Last Sunday of month", childFeatures: '["buggy-friendly","highchairs","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // MANCHESTER
    { title: "Whitworth Tiny Art Explorers", description: "A creative session for under-3s at the Whitworth Art Gallery. Explore textures, colours, and mark-making inspired by the gallery collections.", category: "arts", date: "2026-03-26", startTime: "10:00", endTime: "11:00", venueName: "The Whitworth", address: "Oxford Road, Manchester", city: "Manchester", country: "UK", latitude: 53.4600, longitude: -2.2260, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Buggy Bootcamp Heaton Park", description: "An outdoor fitness class for mums with buggies in Manchester's biggest park. Running, circuits, and core work. Finish with a social coffee at the cafe.", category: "wellness", date: "2026-03-25", startTime: "10:00", endTime: "11:00", venueName: "Heaton Park", address: "Heaton Park, Manchester", city: "Manchester", country: "UK", latitude: 53.5329, longitude: -2.2520, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","parking","baby-changing"]', isFeatured: false },
    { title: "Diddi Dance for Pre-schoolers", description: "A funky, upbeat dance class for 2-5 year olds. Different dance style each term: salsa, disco, hip-hop, bollywood. Great for building coordination and confidence.", category: "classes", date: "2026-03-27", startTime: "09:30", endTime: "10:15", venueName: "Sale Leisure Centre", address: "Sale, Manchester", city: "Manchester", country: "UK", latitude: 53.4234, longitude: -2.3219, cost: 6, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["parking","baby-changing"]', isFeatured: false },
    { title: "Baby Sensory Manchester", description: "A magical world of sensory exploration for babies. Light shows, textured toys, musical instruments, and gentle activities designed to stimulate development.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:45", venueName: "The Lowry Theatre", address: "Pier 8, Salford Quays, Manchester", city: "Manchester", country: "UK", latitude: 53.4708, longitude: -2.2976, cost: 7, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },

    // CARDIFF
    { title: "Bute Park Nature Tots", description: "A woodland adventure for toddlers and pre-schoolers in Cardiff's beautiful Bute Park. Den building, mud kitchen, and nature crafts.", category: "outdoor", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Bute Park", address: "North Road, Cardiff", city: "Cardiff", country: "UK", latitude: 51.4877, longitude: -3.1877, cost: 5, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["parking"]', isFeatured: false },
    { title: "Welsh Nursery Rhymes", description: "Learn traditional Welsh nursery rhymes and songs with your little one. A bilingual session celebrating Welsh language and culture through music.", category: "music", date: "2026-03-27", startTime: "10:30", endTime: "11:00", venueName: "Cardiff Central Library", address: "The Hayes, Cardiff", city: "Cardiff", country: "UK", latitude: 51.4780, longitude: -3.1773, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Little Makers Workshop", description: "A creative workshop for pre-schoolers at the National Museum. Make crafts inspired by museum exhibits. New theme each week.", category: "arts", date: "2026-03-28", startTime: "10:30", endTime: "11:30", venueName: "National Museum Cardiff", address: "Cathays Park, Cardiff", city: "Cardiff", country: "UK", latitude: 51.4867, longitude: -3.1767, cost: 0, currency: "GBP", isFree: true, ageBands: '["preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },

    // CORK
    { title: "Baby Yoga at The Firkin Crane", description: "A gentle baby yoga class in Cork's beautiful heritage dance centre. Stretches and movements to soothe your baby and strengthen your bond.", category: "wellness", date: "2026-03-26", startTime: "10:00", endTime: "11:00", venueName: "Firkin Crane", address: "Shandon, Cork", city: "Cork", country: "Ireland", latitude: 51.9013, longitude: -8.4757, cost: 12, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Fitzgerald's Park Toddler Meetup", description: "A free, informal meetup for parents with toddlers at Cork's loveliest park. Bring a snack and a ball, let the toddlers roam and make friends.", category: "social", date: "2026-03-28", startTime: "10:30", endTime: "12:00", venueName: "Fitzgerald's Park", address: "Mardyke, Cork", city: "Cork", country: "Ireland", latitude: 51.8946, longitude: -8.4906, cost: 0, currency: "EUR", isFree: true, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","parking"]', isFeatured: false },
    { title: "Story Tent at Nano Nagle", description: "A magical storytelling experience inside the beautiful heritage gardens. Professional storytellers bring Irish folk tales to life for little listeners.", category: "storytime", date: "2026-03-27", startTime: "11:00", endTime: "11:45", venueName: "Nano Nagle Place", address: "Douglas Street, Cork", city: "Cork", country: "Ireland", latitude: 51.8950, longitude: -8.4750, cost: 5, currency: "EUR", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },

    // GLASGOW
    { title: "Riverside Museum Family Fun", description: "Explore Glasgow's amazing transport museum with free family activity trails. Sit in old trains, buses, and cars. Brilliant for curious pre-schoolers.", category: "daysout", date: "2026-03-28", startTime: "10:00", endTime: "16:00", venueName: "Riverside Museum", address: "Pointhouse Place, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8654, longitude: -4.3066, cost: 0, currency: "GBP", isFree: true, ageBands: '["toddler","preschooler"]', recurring: false, childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', isFeatured: false },
    { title: "Baby Bounce & Rhyme", description: "A fun, free rhyme time session at Glasgow's Mitchell Library. Action songs, rhymes, and musical instruments for babies and toddlers.", category: "music", date: "2026-03-25", startTime: "10:30", endTime: "11:00", venueName: "Mitchell Library", address: "North Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8648, longitude: -4.2715, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Kelvingrove Art Tots", description: "A relaxed art exploration session for toddlers at the beautiful Kelvingrove Art Gallery. Touch-and-feel activities inspired by the collections.", category: "arts", date: "2026-03-27", startTime: "10:30", endTime: "11:15", venueName: "Kelvingrove Art Gallery", address: "Argyle Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8688, longitude: -4.2907, cost: 0, currency: "GBP", isFree: true, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },

    // BELFAST — COMMUNITY & SPECIALIST
    { title: "Mums & Tots at St Brigid's Parish", description: "A warm and welcoming mum and baby group run by volunteers at St Brigid's Church hall. Tea and toast on arrival, toys for the little ones, and a lovely community of local mums. No need to book, just come along.", category: "community", date: "2026-03-25", startTime: "10:00", endTime: "11:30", venueName: "St Brigid's Parish Hall", address: "Derryvolgie Avenue, Belfast", city: "Belfast", country: "UK", latitude: 54.5780, longitude: -5.9530, cost: 2, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Little Lambs Baby Group", description: "A friendly church-run parent and baby group at Fisherwick Presbyterian. Songs, play, snacks and a cuppa for mum. All faiths and none welcome — it's really about the community.", category: "community", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Fisherwick Presbyterian Church", address: "Chlorine Gardens, Belfast", city: "Belfast", country: "UK", latitude: 54.5830, longitude: -5.9380, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]', isFeatured: true },
    { title: "Baby Yoga with Aisling", description: "A gentle baby yoga class combining massage, stretching, and bonding techniques. Helps with colic, digestion, and sleep. Suitable from 6 weeks to crawling. Mats and props provided.", category: "wellness", date: "2026-03-27", startTime: "10:30", endTime: "11:30", venueName: "The Dovedale Centre", address: "Malone Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5710, longitude: -5.9470, cost: 10, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Sensory Belfast", description: "Award-winning sensory development classes for babies from birth to 13 months. Light shows, bells, textured toys, bubbles, and signing — a wonderful multi-sensory experience for your wee one.", category: "classes", date: "2026-03-26", startTime: "13:30", endTime: "14:15", venueName: "Stormont Hotel", address: "Upper Newtownards Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5883, longitude: -5.8680, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]', isFeatured: false },
    { title: "Parent & Toddler Group at Stormont", description: "A community-run toddler group in the Stormont Estate community room. Crafts, free play, snack time, and a great chance to meet other local parents. Run by parent volunteers.", category: "community", date: "2026-03-27", startTime: "09:30", endTime: "11:00", venueName: "Stormont Estate Community Room", address: "Stormont Estate, Belfast", city: "Belfast", country: "UK", latitude: 54.5939, longitude: -5.8648, cost: 1.5, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },

    // DUBLIN — COMMUNITY & SPECIALIST
    { title: "Mum & Baby Group at Church of the Assumption", description: "A welcoming parish mum and baby drop-in morning. Tea, coffee, and biscuits while the babies play on soft mats. A great way to meet other new mums in the Booterstown area.", category: "community", date: "2026-03-26", startTime: "10:30", endTime: "12:00", venueName: "Church of the Assumption Hall", address: "Booterstown Avenue, Blackrock, Dublin", city: "Dublin", country: "Ireland", latitude: 53.3137, longitude: -6.1892, cost: 0, currency: "EUR", isFree: true, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","parking"]', isFeatured: false },
    { title: "Baby Yoga Dublin with Nurture", description: "A calming baby yoga session blending infant massage, gentle stretches, and guided relaxation. Wonderful for bonding and helping babies who are unsettled. Book of 6 sessions available.", category: "wellness", date: "2026-03-25", startTime: "11:00", endTime: "12:00", venueName: "Rathmines Community Centre", address: "Rathmines Road, Dublin 6", city: "Dublin", country: "Ireland", latitude: 53.3255, longitude: -6.2644, cost: 14, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // LONDON — COMMUNITY & SPECIALIST
    { title: "Stay and Play at St Mary's Church", description: "A bustling, friendly parent and toddler group in the church hall. Soft play area, ride-ons, craft table, and a lovely group of regulars. Tea and coffee included. All welcome.", category: "community", date: "2026-03-25", startTime: "09:30", endTime: "11:30", venueName: "St Mary's Church Hall", address: "Stoke Newington Church Street, London N16", city: "London", country: "UK", latitude: 51.5610, longitude: -0.0780, cost: 2.5, currency: "GBP", isFree: false, ageBands: '["baby","toddler","preschooler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Sensory Islington", description: "A magical multi-sensory adventure for babies from birth. Fibre optic lights, textured toys, bubbles, bells, feathers, and signing songs. Each week follows a different theme.", category: "classes", date: "2026-03-27", startTime: "10:00", endTime: "10:45", venueName: "Islington Assembly Hall", address: "Upper Street, Islington, London N1", city: "London", country: "UK", latitude: 51.5400, longitude: -0.1026, cost: 9, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // EDINBURGH — COMMUNITY & SPECIALIST
    { title: "Wee Ones at Palmerston Place Church", description: "A lovely church-run baby and toddler group in the heart of Edinburgh's West End. Soft play, snack time, music circle to finish. A real lifeline for new parents in the area.", category: "community", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Palmerston Place Church Hall", address: "Palmerston Place, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9503, longitude: -3.2120, cost: 2, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Yoga Edinburgh", description: "A nurturing baby yoga class using gentle holds, stretches, and rocking to soothe and calm your baby. Includes elements of baby massage. Suitable from 6 weeks.", category: "wellness", date: "2026-03-27", startTime: "10:00", endTime: "11:00", venueName: "The Yoga Room Stockbridge", address: "Raeburn Place, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9578, longitude: -3.2094, cost: 10, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // GLASGOW — COMMUNITY & SPECIALIST
    { title: "Mums & Tots at St Andrew's Cathedral", description: "A warm, inclusive baby and toddler group in the cathedral's community hall. Free play, singing time, and refreshments. Run by volunteers from the congregation. All faiths welcome.", category: "community", date: "2026-03-25", startTime: "10:00", endTime: "11:30", venueName: "St Andrew's Cathedral Hall", address: "Clyde Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8570, longitude: -4.2530, cost: 1, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Sensory Glasgow", description: "A rich sensory journey for babies from newborn to 13 months. Discover lights, sounds, textures, and gentle music in a themed session that changes each week. Signing elements included.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:45", venueName: "Gorbals Community Centre", address: "Norfolk Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8520, longitude: -4.2600, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },

    // MANCHESTER — COMMUNITY
    { title: "Little Stars at St Ann's Church", description: "A popular parent and baby group in the heart of Manchester. Story time, messy play, music, and a warm welcome. Hot drinks and biscuits provided. Drop in, no booking needed.", category: "community", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "St Ann's Church Hall", address: "St Ann Street, Manchester", city: "Manchester", country: "UK", latitude: 53.4826, longitude: -2.2459, cost: 2, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // CARDIFF — COMMUNITY
    { title: "Tiny Tots at St David's Hall", description: "A friendly community playgroup for under-3s in central Cardiff. Art corner, sandpit, ride-ons, and a music circle. Run by a lovely team of local parent volunteers.", category: "community", date: "2026-03-25", startTime: "09:30", endTime: "11:00", venueName: "St David's Church Hall", address: "Pendwyallt Road, Cardiff", city: "Cardiff", country: "UK", latitude: 51.5100, longitude: -3.2200, cost: 2, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: false },

    // CORK — COMMUNITY
    { title: "Mum & Baby Morning at St Fin Barre's", description: "A gentle morning gathering for mums with babies in the cathedral community rooms. Soft mats, toys, and a cup of tea while you chat. A wonderfully supportive group of Cork mums.", category: "community", date: "2026-03-26", startTime: "10:30", endTime: "12:00", venueName: "St Fin Barre's Community Rooms", address: "Dean Street, Cork", city: "Cork", country: "Ireland", latitude: 51.8938, longitude: -8.4820, cost: 0, currency: "EUR", isFree: true, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    { title: "Baby Yoga Cork", description: "A soothing baby yoga class with gentle stretches, massage techniques, and breathing exercises. Helps with wind, colic, and sleep. A lovely bonding experience. From 6 weeks to crawling.", category: "wellness", date: "2026-03-27", startTime: "11:00", endTime: "12:00", venueName: "The Yoga Loft", address: "MacCurtain Street, Cork", city: "Cork", country: "Ireland", latitude: 51.9010, longitude: -8.4730, cost: 12, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // ============ BABY SIGNING ============
    // Belfast
    { title: "Sing and Sign Belfast", description: "Learn to communicate with your baby before they can talk. Fun, musical baby signing classes using British Sign Language. Songs, props, and simple signs like 'milk', 'more', and 'all done'. A brilliant way to reduce frustration and bond with your wee one.", category: "classes", date: "2026-03-25", startTime: "10:00", endTime: "10:45", venueName: "Malone Presbyterian Church Hall", address: "Lisburn Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5720, longitude: -5.9460, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Dublin
    { title: "Baby Signing with Lámh", description: "A gentle introduction to baby signing using Lámh, the Irish sign system. Learn signs for everyday words through songs, stories, and play. Wonderful for building early communication and giving your baby a voice before words arrive.", category: "classes", date: "2026-03-26", startTime: "11:00", endTime: "11:45", venueName: "Rathmines Library", address: "Rathmines Road Lower, Dublin 6", city: "Dublin", country: "Ireland", latitude: 53.3258, longitude: -6.2631, cost: 10, currency: "EUR", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // London
    { title: "TinyTalk Baby Signing", description: "Award-winning baby signing classes combining BSL signs with music, sensory play, and social time. Babies from 0-18 months learn signs for everyday objects and actions. A lovely, calm class with a real community feel.", category: "classes", date: "2026-03-27", startTime: "10:30", endTime: "11:15", venueName: "St Paul's Church Hall", address: "Canonbury, Islington, London N1", city: "London", country: "UK", latitude: 51.5440, longitude: -0.0950, cost: 10, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Edinburgh
    { title: "Sing and Sign Edinburgh", description: "A musical baby signing class using British Sign Language. Learn signs through original songs and activities. Helps babies communicate needs like hunger, tiredness, and wanting more. From newborn to pre-verbal toddlers.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:45", venueName: "Stockbridge Church Hall", address: "Saxe Coburg Street, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9575, longitude: -3.2080, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Glasgow
    { title: "Little Signers Glasgow", description: "BSL-based baby signing in a relaxed, friendly setting. Themed sessions with stories, songs, and messy play alongside learning to sign. A wonderful first class for new parents.", category: "classes", date: "2026-03-26", startTime: "13:30", endTime: "14:15", venueName: "Hillhead Library", address: "Byres Road, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8726, longitude: -4.2920, cost: 7, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // ============ BABY & TODDLER SWIMMING ============
    // Belfast
    { title: "Water Babies Belfast", description: "Warm pool baby swimming classes led by qualified instructors. Build water confidence through songs, gentle submersions, and playful exercises. From newborn upwards. A wonderful bonding experience and life skill.", category: "classes", date: "2026-03-26", startTime: "09:30", endTime: "10:00", venueName: "Olympia Leisure Centre", address: "Boucher Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5750, longitude: -5.9600, cost: 15, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["baby-changing","parking"]', isFeatured: true },
    // Dublin
    { title: "Water Babies Dublin", description: "Ireland's most popular baby swimming programme. Warm pools, small class sizes, and a progressive curriculum from newborn to pre-school. Swim nappies essential. Book a term in advance as places fill quickly.", category: "classes", date: "2026-03-27", startTime: "09:00", endTime: "09:30", venueName: "National Aquatic Centre", address: "Snugborough Road, Blanchardstown, Dublin 15", city: "Dublin", country: "Ireland", latitude: 53.3863, longitude: -6.3901, cost: 16, currency: "EUR", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["baby-changing","parking"]', isFeatured: false },
    // London
    { title: "Puddle Ducks Baby Swimming", description: "Small, warm-water baby and toddler swimming classes. Learn through play with songs, toys, and gentle water confidence building. Classes graded by ability, not just age. A lovely Saturday morning routine.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:30", venueName: "Highbury Pool", address: "Highbury Crescent, London N5", city: "London", country: "UK", latitude: 51.5490, longitude: -0.0990, cost: 14, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["baby-changing"]', isFeatured: false },
    // Edinburgh
    { title: "Water Babies Edinburgh", description: "Baby swimming in a warm, private pool. Qualified teachers guide you through water confidence exercises, songs, and gentle submersions. From newborn. A real highlight of the week for many Edinburgh mums.", category: "classes", date: "2026-03-25", startTime: "10:30", endTime: "11:00", venueName: "Edinburgh Leisure Ainslie Park", address: "Pilton Drive, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9670, longitude: -3.2200, cost: 14, currency: "GBP", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["baby-changing","parking"]', isFeatured: false },
    // Cork
    { title: "Water Babies Cork", description: "Baby and toddler swimming in a lovely warm pool. Gentle, fun classes that build water confidence and teach essential water safety. From newborn to 4 years. Swim nappies required.", category: "classes", date: "2026-03-28", startTime: "09:30", endTime: "10:00", venueName: "Leisureworld Bishopstown", address: "Model Farm Road, Cork", city: "Cork", country: "Ireland", latitude: 51.8878, longitude: -8.5150, cost: 15, currency: "EUR", isFree: false, ageBands: '["baby","toddler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["baby-changing","parking"]', isFeatured: false },

    // ============ FOREST SCHOOL / NATURE PLAY ============
    // Belfast
    { title: "Wee Wild Ones Forest Play", description: "Outdoor nature play for toddlers and pre-schoolers in Colin Glen Forest Park. Mud kitchens, den building, bug hunting, and puddle jumping. Dress for the weather and bring spare clothes. A magical morning in the woods.", category: "outdoor", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Colin Glen Forest Park", address: "Stewartstown Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5669, longitude: -5.9940, cost: 6, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["parking"]', isFeatured: false },
    // Dublin
    { title: "Little Explorers Forest School", description: "A nature-based session for under-5s in the beautiful grounds of Marlay Park. Guided by a trained forest school leader. Leaf art, nature trails, mini-beast hunts, and campfire stories. Wellies essential.", category: "outdoor", date: "2026-03-27", startTime: "10:00", endTime: "11:30", venueName: "Marlay Park", address: "Grange Road, Rathfarnham, Dublin 16", city: "Dublin", country: "Ireland", latitude: 53.2792, longitude: -6.2652, cost: 10, currency: "EUR", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["parking"]', isFeatured: false },
    // London
    { title: "Forest Tots Hampstead Heath", description: "A magical forest school session for toddlers and pre-schoolers on Hampstead Heath. Leaf printing, stick dens, nature scavenger hunts, and songs around a campfire circle. A breath of fresh air in the city.", category: "outdoor", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Hampstead Heath", address: "East Heath Road, London NW3", city: "London", country: "UK", latitude: 51.5608, longitude: -0.1631, cost: 8, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '[]', isFeatured: false },
    // Glasgow
    { title: "Muddy Boots Forest Play", description: "Forest school for little ones in Pollok Country Park. Rope swings, mud painting, whittling for older ones, and nature treasure hunts. Run rain or shine by trained outdoor play leaders. Bring waterproofs.", category: "outdoor", date: "2026-03-28", startTime: "10:00", endTime: "11:30", venueName: "Pollok Country Park", address: "Pollokshaws Road, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8310, longitude: -4.3090, cost: 7, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["parking"]', isFeatured: false },
    // Edinburgh
    { title: "Nature Tots at Cramond", description: "A gentle forest school session by the shore at Cramond. Rock pooling, nature art, shell collecting, and outdoor free play. A lovely blend of beach and woodland for adventurous little ones.", category: "outdoor", date: "2026-03-27", startTime: "10:00", endTime: "11:30", venueName: "Cramond Foreshore", address: "Cramond Glebe Road, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9770, longitude: -3.2990, cost: 6, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["parking"]', isFeatured: false },

    // ============ BABY MASSAGE ============
    // Belfast
    { title: "Baby Massage at Sure Start", description: "A free 4-week baby massage course run by a qualified instructor through Sure Start. Learn techniques to soothe colic, aid digestion, and help your baby sleep. Organic oils provided. A calm, nurturing hour.", category: "wellness", date: "2026-03-25", startTime: "14:00", endTime: "15:00", venueName: "Sure Start South Belfast", address: "Donegall Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5910, longitude: -5.9450, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Wednesday (4-week block)", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Dublin
    { title: "Infant Massage Dublin", description: "IAIM-certified baby massage classes in a warm, quiet studio. Learn a full body massage routine over 5 weeks. Helps with sleep, wind, colic, and bonding. Small groups of 6 for personal attention. From 6 weeks.", category: "wellness", date: "2026-03-26", startTime: "14:00", endTime: "15:00", venueName: "The Nurture Rooms", address: "Ranelagh, Dublin 6", city: "Dublin", country: "Ireland", latitude: 53.3284, longitude: -6.2580, cost: 12, currency: "EUR", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Thursday (5-week block)", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Edinburgh
    { title: "Baby Massage at Birthlight", description: "A warm, supportive baby massage class using gentle strokes and yoga-inspired techniques. Promotes bonding, helps with colic and reflux, and gives mums a calm hour in the week. From 4 weeks old.", category: "wellness", date: "2026-03-25", startTime: "13:00", endTime: "14:00", venueName: "The Pregnancy & Parents Centre", address: "Gillespie Crescent, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9420, longitude: -3.2050, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Wednesday (4-week block)", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // Manchester
    { title: "Baby Massage Manchester", description: "A soothing baby massage class in a warm, candlelit studio. Learn techniques to calm your baby, ease teething pain, and improve sleep. Small, friendly groups with tea and chat afterwards.", category: "wellness", date: "2026-03-27", startTime: "10:30", endTime: "11:30", venueName: "The Baby Nest", address: "Chorlton, Manchester", city: "Manchester", country: "UK", latitude: 53.4420, longitude: -2.2720, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby"]', recurring: true, recurrencePattern: "Every Friday (4-week block)", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // ============ TODDLER GYMNASTICS ============
    // Belfast
    { title: "Tumble Tots Belfast", description: "Active, fun gymnastics for walking toddlers and pre-schoolers. Climbing frames, balance beams, rolls, and tumbles on soft equipment. Brilliant for coordination, confidence, and burning off energy.", category: "classes", date: "2026-03-28", startTime: "09:30", endTime: "10:15", venueName: "Shankill Leisure Centre", address: "Shankill Road, Belfast", city: "Belfast", country: "UK", latitude: 54.6030, longitude: -5.9510, cost: 7, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["parking","baby-changing"]', isFeatured: false },
    // Dublin
    { title: "GymBobs Toddler Gym", description: "A fun gymnastics class for toddlers and pre-schoolers. Trampolines, monkey bars, balance beams, and soft play. Develops motor skills, balance, and confidence in a safe, supervised environment.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:45", venueName: "GymBobs", address: "Leopardstown Business Park, Dublin 18", city: "Dublin", country: "Ireland", latitude: 53.2680, longitude: -6.2160, cost: 12, currency: "EUR", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["parking","baby-changing"]', isFeatured: false },
    // London
    { title: "Tumble Tots Islington", description: "The classic toddler gymnastics programme. Colourful climbing equipment, balance challenges, and soft landings. Graded by age so your little one is always appropriately challenged. A Saturday morning institution.", category: "classes", date: "2026-03-28", startTime: "09:30", endTime: "10:15", venueName: "Sobell Leisure Centre", address: "Hornsey Road, London N7", city: "London", country: "UK", latitude: 51.5560, longitude: -0.1120, cost: 9, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["baby-changing","parking"]', isFeatured: false },
    // Manchester
    { title: "Tumble Tots Manchester", description: "Action-packed gymnastics sessions for toddlers. Climbing, rolling, jumping, and balancing on colourful equipment. Brilliant for physical confidence and great fun. Walking to 5 years.", category: "classes", date: "2026-03-28", startTime: "10:00", endTime: "10:45", venueName: "Wythenshawe Forum", address: "Simonsway, Wythenshawe, Manchester", city: "Manchester", country: "UK", latitude: 53.3890, longitude: -2.2640, cost: 7, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["parking","baby-changing"]', isFeatured: false },

    // ============ TODDLER COOKERY ============
    // Belfast
    { title: "Little Bakers Belfast", description: "A hands-on baking class for pre-schoolers. Mixing, pouring, kneading, and decorating — each session makes something delicious to take home. Aprons provided. A lovely way to build fine motor skills and have a tasty treat.", category: "arts", date: "2026-03-27", startTime: "10:00", endTime: "11:00", venueName: "Forestside Community Room", address: "Upper Galwally, Belfast", city: "Belfast", country: "UK", latitude: 54.5590, longitude: -5.9150, cost: 8, currency: "GBP", isFree: false, ageBands: '["preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["parking","baby-changing"]', isFeatured: false },
    // London
    { title: "Mini Chefs Cooking Class", description: "Fun, messy cookery sessions for toddlers and pre-schoolers. Make simple healthy snacks — pizza faces, fruit kebabs, flapjacks. Each child takes home what they've made. Allergy-aware kitchen.", category: "arts", date: "2026-03-25", startTime: "10:00", endTime: "11:00", venueName: "The Cook House", address: "Crouch End, London N8", city: "London", country: "UK", latitude: 51.5780, longitude: -0.1200, cost: 12, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["baby-changing"]', isFeatured: false },
    // Dublin
    { title: "Little Cooks Dublin", description: "A creative cookery class for 3-5 year olds. Measure, mix, taste, and decorate. Each week has a different theme — from fairy cakes to veggie wraps. A wonderful activity for developing independence and confidence.", category: "arts", date: "2026-03-28", startTime: "10:30", endTime: "11:30", venueName: "Pearse Street Library", address: "Pearse Street, Dublin 2", city: "Dublin", country: "Ireland", latitude: 53.3432, longitude: -6.2475, cost: 8, currency: "EUR", isFree: false, ageBands: '["preschooler"]', recurring: true, recurrencePattern: "Every Saturday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },

    // ============ TODDLER LANGUAGE CLASSES ============
    // Belfast
    { title: "Little Lingos Irish Language Play", description: "A playful introduction to Irish through songs, games, puppets, and stories. No prior Irish needed from parents. A fun way to expose little ones to the language and culture. Suitable from 2 years.", category: "classes", date: "2026-03-25", startTime: "10:00", endTime: "10:45", venueName: "Cultúrlann McAdam Ó Fiaich", address: "Falls Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5969, longitude: -5.9620, cost: 5, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    // Dublin
    { title: "Naíonra Pop-Up Playgroup", description: "An Irish-language toddler playgroup run through the medium of Irish. Singing, art, free play, and stories as Gaeilge. A wonderful immersive experience even if your Irish is rusty. From 18 months.", category: "classes", date: "2026-03-26", startTime: "10:00", endTime: "11:30", venueName: "Conradh na Gaeilge", address: "Harcourt Street, Dublin 2", city: "Dublin", country: "Ireland", latitude: 53.3341, longitude: -6.2613, cost: 5, currency: "EUR", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Thursday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    // Cardiff
    { title: "Cylch Ti a Fi Welsh Playgroup", description: "A Welsh-language parent and toddler group. Songs, stories, and play through the medium of Welsh. A lovely, relaxed way to introduce your little one to the Welsh language, regardless of your own level.", category: "community", date: "2026-03-25", startTime: "10:00", endTime: "11:30", venueName: "Mudiad Meithrin Centre", address: "Cathedral Road, Cardiff", city: "Cardiff", country: "UK", latitude: 51.4830, longitude: -3.1900, cost: 2, currency: "GBP", isFree: false, ageBands: '["baby","toddler","preschooler"]', recurring: true, recurrencePattern: "Every Wednesday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },
    // London
    { title: "Le Petit Club French Playgroup", description: "A French language playgroup for little ones. Native-speaking teachers lead songs, crafts, stories, and games entirely in French. A wonderful early exposure to a second language through play. From 18 months.", category: "classes", date: "2026-03-27", startTime: "10:00", endTime: "10:45", venueName: "The French Institute", address: "South Kensington, London SW7", city: "London", country: "UK", latitude: 51.4955, longitude: -0.1730, cost: 12, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing"]', isFeatured: false },
    // Glasgow
    { title: "Gaelic Tots Playgroup", description: "A Gaelic-medium playgroup for babies and toddlers. Traditional Scottish songs, play, and stories in Gaelic. No Gaelic needed from parents — a welcoming, fun way to hear the language from birth.", category: "community", date: "2026-03-27", startTime: "10:00", endTime: "11:30", venueName: "Glasgow Gaelic School", address: "Berkeley Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8670, longitude: -4.2740, cost: 0, currency: "GBP", isFree: true, ageBands: '["baby","toddler","preschooler"]', recurring: true, recurrencePattern: "Every Friday", childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', isFeatured: false },

    // SEASONAL
    { title: "Easter Egg Hunt at Belfast Castle", description: "A magical Easter egg hunt in the grounds of Belfast Castle. Follow the clues, find the eggs, and enjoy face painting, crafts, and a visit from the Easter Bunny.", category: "seasonal", date: "2026-04-05", startTime: "10:00", endTime: "14:00", venueName: "Belfast Castle", address: "Antrim Road, Belfast", city: "Belfast", country: "UK", latitude: 54.6373, longitude: -5.9418, cost: 5, currency: "GBP", isFree: false, ageBands: '["toddler","preschooler"]', recurring: false, childFeatures: '["buggy-friendly","baby-changing","parking"]', isFeatured: true },
    { title: "Spring Lambing Day", description: "Meet the new spring lambs at this family farm open day. Bottle feed lambs, see chicks hatching, and enjoy tractor rides. A wonderful spring day out.", category: "seasonal", date: "2026-04-04", startTime: "10:00", endTime: "15:00", venueName: "Streamvale Open Farm", address: "Dundonald, Belfast", city: "Belfast", country: "UK", latitude: 54.5656, longitude: -5.8557, cost: 8, currency: "GBP", isFree: false, ageBands: '["baby","toddler","preschooler"]', recurring: false, childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', isFeatured: true },
  ];

  for (const event of seedEvents) {
    db.insert(events).values(event).run();
  }

  // ============ PLACES ============

  const seedPlaces = [
    // BELFAST
    { name: "W5 at Odyssey", description: "Northern Ireland's award-winning science and discovery centre. Interactive exhibits, a dedicated toddler area, and regular family workshops. A rainy day favourite.", category: "daysout", address: "2 Queen's Quay, Belfast", city: "Belfast", country: "UK", latitude: 54.6054, longitude: -5.9198, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', openingHours: "Mon-Sat 10:00-17:00, Sun 12:00-18:00", website: "https://w5online.co.uk", isFeatured: true },
    { name: "Ormeau Park", description: "A beautiful Victorian park with a wonderful enclosed playground for young children. Swings, slides, climbing frames, and lots of green space for running about.", category: "parks", address: "Ormeau Road, Belfast", city: "Belfast", country: "UK", latitude: 54.5802, longitude: -5.9148, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","parking"]', openingHours: "Dawn to dusk daily", isFeatured: false },
    { name: "Ulster Museum", description: "A brilliant free museum with a dedicated Early Years space. Dinosaurs, art, Egyptian mummies, and nature collections. The Discovery Zone is perfect for curious pre-schoolers.", category: "daysout", address: "Botanic Gardens, Belfast", city: "Belfast", country: "UK", latitude: 54.5852, longitude: -5.9308, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', openingHours: "Tue-Sun 10:00-17:00", isFeatured: false },
    { name: "Jungle NI Soft Play", description: "Belfast's largest indoor soft play centre with a dedicated baby area, toddler zone, and bigger frame for pre-schoolers. Cafe with highchairs and baby food options.", category: "indoor", address: "Dundonald, Belfast", city: "Belfast", country: "UK", latitude: 54.5725, longitude: -5.8623, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["baby-changing","parking","highchairs"]', openingHours: "Daily 10:00-18:00", isFeatured: false },
    { name: "Established Coffee", description: "One of Belfast's best speciality coffee shops with a genuinely family-friendly atmosphere. Space for buggies, highchairs available, and a relaxed vibe perfect for a coffee with your little one.", category: "cafes", address: "54 Hill Street, Belfast", city: "Belfast", country: "UK", latitude: 54.6019, longitude: -5.9284, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","highchairs","breastfeeding-welcome"]', openingHours: "Mon-Sat 08:00-17:00, Sun 09:00-17:00", isFeatured: false },

    // DUBLIN
    { name: "Imaginosity", description: "Dublin's interactive children's museum designed for ages 1-9. Climbing, building, role-playing, and creative exploration across multiple themed zones.", category: "daysout", address: "Beacon South Quarter, Sandyford, Dublin 18", city: "Dublin", country: "Ireland", latitude: 53.2710, longitude: -6.2187, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', openingHours: "Wed-Sun 09:30-17:30", website: "https://imaginosity.ie", isFeatured: true },
    { name: "National Botanic Gardens", description: "Stunning free gardens with glasshouses, walking paths, and wide open spaces. Perfect for a buggy stroll or letting toddlers explore the sensory garden.", category: "parks", address: "Glasnevin, Dublin 9", city: "Dublin", country: "Ireland", latitude: 53.3723, longitude: -6.2669, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking"]', openingHours: "Daily 09:00-17:00 (summer 18:00)", isFeatured: false },
    { name: "Dublin Zoo", description: "One of the oldest zoos in Europe with over 400 animals. The family farm area lets little ones get close to gentle animals. Regular keeper talks and feeding times.", category: "daysout", address: "Phoenix Park, Dublin 8", city: "Dublin", country: "Ireland", latitude: 53.3549, longitude: -6.3043, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', openingHours: "Daily 09:30-16:30", website: "https://dublinzoo.ie", isFeatured: true },
    { name: "The Ark Cultural Centre", description: "Europe's only purpose-built cultural centre for children. Theatre, art, music, and creative workshops designed specifically for young audiences.", category: "daysout", address: "Eustace Street, Temple Bar, Dublin 2", city: "Dublin", country: "Ireland", latitude: 53.3459, longitude: -6.2659, ageBands: '["preschooler"]', childFeatures: '["buggy-friendly","baby-changing"]', openingHours: "Check website for event times", website: "https://ark.ie", isFeatured: false },

    // LONDON
    { name: "Diana Memorial Playground", description: "A magical pirate ship-themed playground in Kensington Gardens. The giant wooden ship, teepees, and sensory trail make this one of London's best playgrounds for young children.", category: "parks", address: "Kensington Gardens, London W2", city: "London", country: "UK", latitude: 51.5087, longitude: -0.1870, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing"]', openingHours: "Daily 10:00-17:45", isFeatured: true },
    { name: "Coram's Fields", description: "A unique seven-acre park and playground in central London. Adults can only enter with a child. Under-5s area, sandpit, paddling pool, and city farm.", category: "parks", address: "93 Guilford Street, London WC1N", city: "London", country: "UK", latitude: 51.5244, longitude: -0.1210, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', openingHours: "Daily 09:00-dusk", isFeatured: false },
    { name: "Natural History Museum", description: "Free entry to one of the world's greatest museums. The dinosaur gallery is unforgettable. Excellent baby changing facilities and a dedicated family area.", category: "daysout", address: "Cromwell Road, London SW7", city: "London", country: "UK", latitude: 51.4967, longitude: -0.1764, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","highchairs"]', openingHours: "Daily 10:00-17:50", isFeatured: false },

    // EDINBURGH
    { name: "Royal Botanic Garden Edinburgh", description: "70 acres of stunning gardens free to explore. Wide buggy-friendly paths, a wonderful rock garden, and seasonal events for families.", category: "parks", address: "Inverleith Row, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9652, longitude: -3.2088, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking"]', openingHours: "Daily 10:00-17:00 (summer 18:00)", isFeatured: false },
    { name: "National Museum of Scotland", description: "Free entry to an incredible museum with interactive galleries perfect for young children. The Animal World and Explore zones are toddler favourites.", category: "daysout", address: "Chambers Street, Edinburgh", city: "Edinburgh", country: "UK", latitude: 55.9470, longitude: -3.1900, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome","highchairs"]', openingHours: "Daily 10:00-17:00", isFeatured: true },

    // MANCHESTER
    { name: "Whitworth Art Gallery", description: "A beautiful free gallery set in a park. Regular family-friendly workshops and a relaxed cafe. The park grounds are perfect for a post-visit run around.", category: "daysout", address: "Oxford Road, Manchester", city: "Manchester", country: "UK", latitude: 53.4600, longitude: -2.2260, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing"]', openingHours: "Thu-Sun 10:00-17:00", isFeatured: false },
    { name: "Heaton Park", description: "Manchester's largest park with an animal centre, boating lake, and huge open spaces. The adventure playground is brilliant for pre-schoolers. Free entry.", category: "parks", address: "Heaton Park, Manchester", city: "Manchester", country: "UK", latitude: 53.5329, longitude: -2.2520, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","parking","baby-changing"]', openingHours: "Dawn to dusk daily", isFeatured: false },

    // CORK
    { name: "Fitzgerald's Park", description: "Cork's most beautiful park with a wonderful playground, pond, and cafe. The Cork Public Museum is also here with free entry. Brilliant for a family morning out.", category: "parks", address: "Mardyke, Cork", city: "Cork", country: "Ireland", latitude: 51.8946, longitude: -8.4906, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking"]', openingHours: "Dawn to dusk daily", isFeatured: false },
    { name: "Fota Wildlife Park", description: "An open-plan wildlife park where animals roam freely. Lemurs, penguins, giraffes, and more. The perfect day out for animal-loving little ones.", category: "daysout", address: "Fota Island, Carrigtwohill, Cork", city: "Cork", country: "Ireland", latitude: 51.8923, longitude: -8.3067, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","parking","highchairs"]', openingHours: "Daily 10:00-16:30", website: "https://fotawildlife.ie", isFeatured: true },

    // GLASGOW
    { name: "Kelvingrove Art Gallery and Museum", description: "One of Scotland's most popular free museums. The interactive exhibits, wildlife displays, and regular family events make it a wonderful rainy-day destination.", category: "daysout", address: "Argyle Street, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8688, longitude: -4.2907, ageBands: '["toddler","preschooler"]', childFeatures: '["buggy-friendly","baby-changing","breastfeeding-welcome"]', openingHours: "Mon-Thu & Sat 10:00-17:00, Fri & Sun 11:00-17:00", isFeatured: false },
    { name: "Glasgow Botanic Gardens", description: "Beautiful free gardens with stunning Victorian glasshouses. Wide paths perfect for buggies, and the herb garden is a lovely sensory experience for little ones.", category: "parks", address: "Great Western Road, Glasgow", city: "Glasgow", country: "UK", latitude: 55.8782, longitude: -4.2888, ageBands: '["baby","toddler","preschooler"]', childFeatures: '["buggy-friendly"]', openingHours: "Daily 07:00-dusk, Glasshouses 10:00-16:00", isFeatured: false },
  ];

  for (const place of seedPlaces) {
    db.insert(places).values(place).run();
  }

  // Insert new location seed data (169 events + 63 places)
  for (const event of newEvents) {
    db.insert(events).values(event).run();
  }

  for (const place of newPlaces) {
    db.insert(places).values(place).run();
  }

  // Insert real verified community groups
  for (const event of realEvents) {
    db.insert(events).values(event).run();
  }

  for (const place of realPlaces) {
    db.insert(places).values(place).run();
  }

  // ============ SPONSORS (Local Partners) ============
  const seedSponsors = [
    { name: "Little Nest Baby Boutique", tagline: "Beautiful essentials for your little one", category: "Baby Shop", city: "Belfast", website: "https://example.com", logoEmoji: "👶", isActive: true },
    { name: "Tumble Town Soft Play", tagline: "Indoor fun for tiny adventurers", category: "Soft Play", city: "Dublin", website: "https://example.com", logoEmoji: "🎠", isActive: true },
    { name: "The Cosy Cup Café", tagline: "Family-friendly brews & bakes", category: "Café", city: "Belfast", website: "https://example.com", logoEmoji: "☕", isActive: true },
    { name: "Wee Ones Swim School", tagline: "Building water confidence from birth", category: "Swimming", city: "Edinburgh", website: "https://example.com", logoEmoji: "🏊", isActive: true },
    { name: "Blossom & Grow Nursery", tagline: "Where little minds flourish", category: "Nursery", city: "Manchester", website: "https://example.com", logoEmoji: "🌸", isActive: true },
    { name: "Tiny Steps Photography", tagline: "Capturing your family's precious moments", category: "Photography", city: "London", website: "https://example.com", logoEmoji: "📷", isActive: true },
  ];

  for (const sponsor of seedSponsors) {
    db.insert(sponsors).values(sponsor).run();
  }

  // ============ SEED REACTIONS & REVIEWS ============
  // Get all event IDs after insertion
  const allInsertedEvents = db.select().from(events).all();
  const eventIds = allInsertedEvents.map(e => e.id);

  // Seed reactions for ~40% of events (varied counts)
  const reactionNames = [
    "sess_demo_anna", "sess_demo_claire", "sess_demo_emma", "sess_demo_sophie",
    "sess_demo_rachel", "sess_demo_kate", "sess_demo_fiona", "sess_demo_laura",
    "sess_demo_megan", "sess_demo_niamh", "sess_demo_siobhan", "sess_demo_aoife",
    "sess_demo_ciara", "sess_demo_grace", "sess_demo_holly",
  ];

  let reactionCount = 0;
  for (const eventId of eventIds) {
    // ~40% of events get reactions
    if (Math.random() > 0.40) continue;
    const numBeenThere = Math.floor(Math.random() * 10) + 1; // 1-10
    const numRecommend = Math.floor(Math.random() * Math.min(numBeenThere, 8)) + 1; // 1 to min(beenThere,8)
    for (let i = 0; i < numBeenThere; i++) {
      db.insert(reactions).values({
        eventId,
        type: "been_there",
        sessionId: reactionNames[i % reactionNames.length] + "_" + eventId,
        createdAt: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
      }).run();
      reactionCount++;
    }
    for (let i = 0; i < numRecommend; i++) {
      db.insert(reactions).values({
        eventId,
        type: "recommend",
        sessionId: reactionNames[i % reactionNames.length] + "_" + eventId,
        createdAt: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
      }).run();
      reactionCount++;
    }
  }

  // Seed reviews for ~20% of events (1-3 reviews each)
  const reviewSnippets = [
    { name: "Anna, mum of 1", text: "Lovely session, my wee one absolutely loved it" },
    { name: "Claire, mum of 2", text: "So welcoming and relaxed, perfect for first-timers" },
    { name: "Emma, Belfast mum", text: "We go every week now, brilliant for babies" },
    { name: "Sophie, mum of twins", text: "Great space and the staff are really friendly" },
    { name: "Rachel M", text: "My toddler didn't want to leave! Will definitely be back" },
    { name: "Kate, new mum", text: "Met some lovely mums here, really helped with the loneliness" },
    { name: "Fiona, mum of 3", text: "Affordable and fun, my pre-schooler asks to go every day" },
    { name: "Laura, first-time mum", text: "Wish I'd found this sooner, such a lovely community" },
    { name: "Niamh, Dublin mum", text: "Brilliant for sensory play, my baby was mesmerised" },
    { name: "Siobhan", text: "Easy to get to with the buggy, nice and spacious" },
    { name: "Aoife, mum of 1", text: "The singing was adorable, my little one clapped along" },
    { name: "Grace, London mum", text: "A hidden gem, so glad a friend recommended it" },
    { name: "Holly, Edinburgh mum", text: "Perfect rainy day activity, well organised too" },
    { name: "Megan, Manchester mum", text: "We've been three times now, never disappoints" },
    { name: "Ciara, Cork mum", text: "Lovely calm atmosphere, baby-friendly through and through" },
  ];

  let reviewCount = 0;
  for (const eventId of eventIds) {
    if (Math.random() > 0.20) continue;
    const numReviews = Math.floor(Math.random() * 3) + 1; // 1-3 reviews
    const shuffled = [...reviewSnippets].sort(() => Math.random() - 0.5);
    for (let i = 0; i < numReviews; i++) {
      const snippet = shuffled[i % shuffled.length];
      db.insert(reviews).values({
        eventId,
        displayName: snippet.name,
        text: snippet.text,
        sessionId: "sess_demo_review_" + eventId + "_" + i,
        createdAt: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
      }).run();
      reviewCount++;
    }
  }

  const totalEvents = seedEvents.length + newEvents.length + realEvents.length;
  const totalPlaces = seedPlaces.length + newPlaces.length + realPlaces.length;
  console.log(`Seeded ${totalEvents} events, ${totalPlaces} places (including ${realEvents.length} real community groups), ${seedSponsors.length} sponsors, ${reactionCount} reactions, and ${reviewCount} reviews.`);
}
